### ISSUE TITLE
TeaLeaf MPI+OpenCL giving NaNs on CPU

### ISSUE THREAD

**Issue by gihanmudalige** [OP-DSL/OPS#114]
Currently, MPI+OpenCL when run on the CPU with more than 1 processor produces NaNs and the test fails. This problem is not there in any other application nor in MPI+OpenCL on GPUs

**Comment by Ashutosh-Londhe** [comment]
@gihanmudalige i think we can close this now.

**Comment by gihanmudalige** [comment]
Yes ok.
