### ISSUE TITLE
Unable to build examples

### ISSUE THREAD

**Issue by chintagunta** [OP-DSL/OPS#128]
Dear OPS team,

I am looking at OPS to incorporate into my CFD code. I am unable to compile the examples. The following errors occur with gnu 7.5 (for every example).
Thank you for your help.

Kind regards,
Dr Abhishek

rm -f *.o *.mod
gfortran  -ffree-form -ffree-line-length-none -J/home/abhi/OPS/fortran/mod/gnu -I/home/abhi/OPS/fortran/mod/gnu  -L/home/abhi/OPS/fortran/lib -lstdc++ constants.F90 MPI/*_seq_kernel.F90 mblock_ops.F90 \
-o mblock_seq -lops_for_seq 
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `ops_construct_tile_plan()':
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o):/usr/include/c++/7/ext/new_allocator.h:125: more undefined references to `operator delete(void*)' follow
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `ops_construct_tile_plan()':
/usr/include/c++/7/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/include/c++/7/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/include/c++/7/ext/new_allocator.h:102: undefined reference to `std::__throw_bad_alloc()'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `std::vector<ops_kernel_descriptor*, std::allocator<ops_kernel_descriptor*> >::~vector()':
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >::~vector()':
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o):/usr/include/c++/7/ext/new_allocator.h:125: more undefined references to `operator delete(void*)' follow
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `void std::vector<ops_kernel_descriptor*, std::allocator<ops_kernel_descriptor*> >::_M_realloc_insert<ops_kernel_descriptor* const&>(__gnu_cxx::__normal_iterator<ops_kernel_descriptor**, std::vector<ops_kernel_descriptor*, std::allocator<ops_kernel_descriptor*> > >, ops_kernel_descriptor* const&)':
/usr/include/c++/7/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `std::vector<tiling_plan, std::allocator<tiling_plan> >::_M_default_append(unsigned long)':
/usr/include/c++/7/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o):/usr/include/c++/7/ext/new_allocator.h:125: more undefined references to `operator delete(void*)' follow
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `std::vector<tiling_plan, std::allocator<tiling_plan> >::_M_default_append(unsigned long)':
/usr/include/c++/7/bits/stl_vector.h:1505: undefined reference to `std::__throw_length_error(char const*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `std::vector<unsigned long, std::allocator<unsigned long> >::_M_default_append(unsigned long)':
/usr/include/c++/7/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `std::vector<unsigned long, std::allocator<unsigned long> >::_M_default_append(unsigned long)':
/usr/include/c++/7/bits/stl_vector.h:1505: undefined reference to `std::__throw_length_error(char const*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >::_M_default_append(unsigned long)':
/usr/include/c++/7/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >::_M_default_append(unsigned long)':
/usr/include/c++/7/bits/stl_vector.h:1505: undefined reference to `std::__throw_length_error(char const*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `std::vector<int, std::allocator<int> >::_M_default_append(unsigned long)':
/usr/include/c++/7/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `std::vector<int, std::allocator<int> >::_M_default_append(unsigned long)':
/usr/include/c++/7/bits/stl_vector.h:1505: undefined reference to `std::__throw_length_error(char const*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o): In function `void std::vector<ops_dat_core*, std::allocator<ops_dat_core*> >::_M_realloc_insert<ops_dat_core* const&>(__gnu_cxx::__normal_iterator<ops_dat_core**, std::vector<ops_dat_core*, std::allocator<ops_dat_core*> > >, ops_dat_core* const&)':
/usr/include/c++/7/ext/new_allocator.h:111: undefined reference to `operator new(unsigned long)'
/usr/include/c++/7/ext/new_allocator.h:125: undefined reference to `operator delete(void*)'
/home/abhi/OPS/fortran/lib/libops_for_seq.a(ops_lazy.o):(.data.rel.local.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
/home/abhi/OPS/makefiles/Makefile.f_app:30: recipe for target 'mblock_seq' failed

**Comment by reguly** [comment]
Dear Dr. Abhishek,

This appears to be an issue with linking libstdc++ as the same compilation command works well elsewhere, but for your system, the order of libraries may be important. Can you please try the following:
`gfortran -ffree-form -ffree-line-length-none -J/home/abhi/OPS/fortran/mod/gnu -I/home/abhi/OPS/fortran/mod/gnu -L/home/abhi/OPS/fortran/lib constants.F90 MPI/_seq_kernel.F90 mblock_ops.F90 -o mblock_seq -lops_for_seq  -lstdc++`
and let me know if that succeeds? If so, I will patch the makefiles to produce the same thing

**Comment by chintagunta** [comment]
Thank you very much for your prompt reply and the fix, Dr Reguly, its working.
