### ISSUE TITLE
fortran+shsgc+unable to generate MPI version

### ISSUE THREAD

**Issue by svkls** [OP-DSL/OPS#131]
when I make apps/fortran/shsgc,something wrong happend : gfortran: error: unrecognized command line option ‘-module’.I use the Intel compiler  and I checked the makefile :Makefile.intel,FFLAGS  = -module $(F_INC_MOD).So can anybody know what can I do for this problem,and what's meaning of the option "-module".By the way ,my Intel compiler is not managed by module.Thank you so much

**Comment by reguly** [comment]
This application uses the mpi90 compiler (an MPI wrapper), which it seems for you wraps gfortran instead of ifort. If you use e.g. OpenMPI, you can do `export OMPI_FC=ifort` which will then make mpif90 use ifort underneath. The `-module` parameter tells the compiler where to find F90 module files (`.mod` files)

**Comment by svkls** [comment]
Thank you for your reply . I use the MPI that comes with intel compiler ,and when I make /apps/fortran/shsgc,something wrong happend : gfortran: error: unrecognized command line option ‘-module’. I checked the compilation information,It is mpif90 unrecognized command line option -module ,so is this a problem with my MPI version ? Looking forward to your reply,thank you

**Comment by svkls** [comment]
Thank you for your reply! I have solved this problem.I use the MPI  that comes with the intel compiler. When I make /apps/fortran/shsgc , it has some problem,so I checked the compilation information ,and I found the mpif90 can't recognize the option -module . Then I modified the Makefile.mpi. I changed mpif90 to mpiifort and it worked.
