### ISSUE TITLE
Silent failure of code generation with ops_decl_dat when using non literal names and types

### ISSUE THREAD

**Issue by csbrady-warwick** [OP-DSL/OPS#138]
**Observed behaviour**
ops_decl_const for C appears to expect the _name_ and _type_ parameters to be character literals because of how they are used during code generation. Using char* variables causes a silent failure during code generation where the generated code uses the name of the variable rather than the content. This is inevitable because of code being generated before runtime but the error is silent at code generation and produces unusual errors at code compile time. Documentation does not make this clear

**Correct behaviour**
Assuming that I am correct and charcter literals are required and are intended to be required then OPS generator should fail with an error message when _name_ and _type_ aren't character literals. Documentation should mention the restriction. Attached patch fixes both. Request review of patch as suitable for inclusion

**Remaining question**
OPS Fortran generator appears to do nothing with ops_decl_const so this error does not appear to apply there. Unclear if this is correct.

[fix.txt](https://github.com/OP-DSL/OPS/files/5903964/fix.txt)

**Comment by reguly** [comment]
Thank you for addressing this!

**Comment by reguly** [comment]
Pulled in the fix for C. Fortran backend is up for discussion, will be handled separately.
