### ISSUE TITLE
Incorrect filename generated for OPS MPI implementation of ops_print_dat_to_txtfile

### ISSUE THREAD

**Issue by csbrady-warwick** [OP-DSL/OPS#140]
**Observed Behaviour**
If a filename of "out.txt" is specified in a call to ops_print_dat_to_txtfile and then OPS is used to generate MPI code then output files named "out.txt.n.{unprintable_character}" are generated where **n** is the MPI rank of the generating MPI process. The unprintable character has the byte value of the MPI rank of the generating MPI process. For more than 255 MPI processes duplicate filenames are generated.

**Expected Behaviour**
If a filename of "out.txt" is specified in a call to ops_print_dat_to_txtfile then output files named "out.txt.n" where **n** is the MPI rank of the generating process.

**Fix**
Attached patch fixes error by replacing erroneous adding of integer to std::string with a call to std::to_string in ops/c/src/mpi/ops_mpi_core.cpp. Also removes duplicate appending of rank number in /ops/c/src/mpi/ops_mpi_decl.cpp. Equivalent code in /ops/c/src/mpi/ops_mpi_decl_cuda.cpp and /ops/c/src/mpi/ops_mpi_decl_opencl.cpp do not have this error but are still affected by the error in ops_mpi_core.cpp

[fix.txt](https://github.com/OP-DSL/OPS/files/6010876/fix.txt)

**Comment by gihanmudalige** [comment]
Thanks @csbrady-warwick. Would you mind making a pull request ?

**Comment by csbrady-warwick** [comment]
No problem. Pull request created.
