### ISSUE TITLE
CUDA problem for big mesh size and multi-dim dat on a single GPU

### ISSUE THREAD

**Issue by jpmeng** [OP-DSL/OPS#147]
It seems that the CUDA code raises an exception about an illegal memory access on a single GPU when the mesh size is beyond a certain value.  When the size is about 33*33*33 (seems up to 128*128*128) the code runs normally (CPU codes as well)., while the ops_dat is 19-long double number.  Beyond this, we get the following with 256*256*256. 

KerCopyf_cuda_kernel.cu(169) : cutilSafeCall() Runtime API error : an illegal memory access was encountered.
terminate called after throwing an instance of 'OPSException'
  what():  an illegal memory access was encountered
[1]    1732705 abort (core dumped)  ./Cavity3DCuda 

With 164*164*164 we get this 

KerCutCellEQMDiffuseRefl3D_cuda_kernel.cu(298) : cutilSafeCall() Runtime API error : an illegal memory access was encountered.
terminate called after throwing an instance of 'OPSException'
  what():  an illegal memory access was encountered

which is called later than the KerCopyf_cuda_kernel.cu. 

I checked the memory allocation (about 7~8GB), which seems still below the capacity of the GPU (32GB) and CPU memory (96GB).

**Comment by reguly** [comment]
Hi Jianping - could you share a repro case?

**Comment by jpmeng** [comment]
Hi Istvan, Thanks. the code repo please see https://github.com/jpmeng/MPLB and the Cavity3D apps there. But the translation replies on a modified ops.py https://github.com/jpmeng/OPS/tree/JSONConfig, since I found a few minor problems on the process for the multidm ops_dat (may be problems here?).  Also the CMake rely on the OPS CMake package configuration which I did a pull request yesterday. Perhaps, I extract the translated files and send to you? 

If you have a slot next week, we can set up a meeting to explain. 

Jianping
