### ISSUE TITLE
Questions about multi-GPU 

### ISSUE THREAD

**Issue by Ahdhn** [OP-DSL/OPS#163]
I have two questions with regard to multi-GPU support in OPS 

1. Using CUDA, how to enable multi-GPU execution of the code? I see that there is a CMake variable [`GPU_NUMBER`](https://github.com/OP-DSL/OPS/blob/develop/CMakeLists.txt#L229) but setting it to more than 1 does _not_ impact the execution at all. For example, after setting  `GPU_NUMBER` to 2 and compiling [Poisson](https://github.com/OP-DSL/OPS/tree/develop/apps/c/poisson) app, I could see (from Nisght System) that  `poisson_cuda` executable only run on a single GPU. Can you give specific instructions on how to run this app on multi-GPU?

2. Does OPS automatically optimize the code by overlapping computation and communication on multi-GPU? For example, with stencil operations, it is possible to overlap part of the computation with the memory transfer of the halo. Can OPS do this automatically? or does such optimization left for the user to implement?

**Comment by reguly** [comment]
1. there should be a poisson_mpi_cuda target which does this, assuming CMake could find MPI. @jpmeng any tricks here to make sure?
2. It currently does not, and the user has no way to implement this, because OPS abstracts away distributed memory parallelism. This optimisation is on the TODO list, we just haven't gotten around to doing it

**Comment by Ahdhn** [comment]
Thank you for the prompt response! 

For 1., does it have to be CUDA-aware MPI?

**Comment by reguly** [comment]
It does not. But if you do have it, you can tell OPS at runtime to use GPU direct comms with the -gpudirect runtime flag

**Comment by Ahdhn** [comment]
Thank you!
