### ISSUE TITLE
Access to ops_arg::dim inside CUDA kernels if the aprameter is not an integer literal in the ops_arg_dat call

### ISSUE THREAD

**Issue by bgd54** [OP-DSL/OPS#164]
Code generator uses arg.dim as a fallback if the dimension is unknown at generation time, but we shouldn't access it from the device.
(see https://github.com/OP-DSL/OPS/blob/668d54f3651e4c4e4e91d94ae4f3dc7c8138c1bb/ops_translator/c/ops_gen_mpi_cuda.py#L385)
The dimension should be passed to the kernels as a function parameter.

**Comment by Ashutosh-Londhe** [comment]
@reguly i think we can close this now. dim is now stored in MANAGED variable which can be accessed in DEVICE function also if required
