### ISSUE TITLE
OPS_ACCxx limited to 0 to 99. Need increased limits.

### ISSUE THREAD

**Issue by gihanmudalige** [OP-DSL/OPS#172]
opensbliblock00_kernels.h:1299:18: error: ‘OPS_ACC108’ was not declared in this scope; did you mean ‘OPS_ACC10’?
 1299 |     Residual0_B0[OPS_ACC108(0,0,0)] = -rc6*(D11_B0[OPS_ACC23(0,0,0)]*wk66_B0[OPS_ACC89(0,0,0)] +
      |                  ^~~~~~~~~~
      |                  OPS_ACC10

opensbliblock00_kernels.h:1306:18: error: ‘OPS_ACC106’ was not declared in this scope; did you mean ‘OPS_ACC10’?
 1306 |     Residual1_B0[OPS_ACC106(0,0,0)] = -rc6*(D11_B0[OPS_ACC23(0,0,0)]*wk66_B0[OPS_ACC89(0,0,0)] +
      |                  ^~~~~~~~~~
      |                  OPS_ACC10

opensbliblock00_kernels.h:1313:18: error: ‘OPS_ACC105’ was not declared in this scope; did you mean ‘OPS_ACC10’?
 1313 |     Residual2_B0[OPS_ACC105(0,0,0)] = -rc6*(D11_B0[OPS_ACC23(0,0,0)]*wk66_B0[OPS_ACC89(0,0,0)] +

OPS_ACCxx are limited to xx from 0 to 99. Need to increase limit.

**Comment by reguly** [comment]
Please use the new v2 API with the ACC objects, where this is not an issue

**Comment by gihanmudalige** [comment]
This is an issue with code generated with OpenSBLI, which uses the old API. I think OpenSBLI has not moved to using the new ACC objects.

**Comment by dl11g11** [comment]
I added the v2 OPS API as an option in our code-generation a while ago, but I think some users are still using the old format. I'll add the change to our public release once I've tested for this xx>99 case.
