### ISSUE TITLE
Discripany with cmake build and makefile build of OPS

### ISSUE THREAD

**Issue by benielT** [OP-DSL/OPS#180]
I tried to use cmake build as mentioned in https://ops-dsl.readthedocs.io/en/latest/installation.html#build-library-and-example-applications-separately. But the generated library is placed within `$(OPS_INSTALL_PATH)/lib`, header files within `$(OPS_INSTALL_PATH)/include` and binaries within `$(OPS_INSTALL_PATH)/bin`.  In the other hand building app manually using the given makefiles in OPS, expecting the libraries to be in `$(OPS_INSTALL_PATH)/c/lib/$(OPS_COMPILER)`.

In the other hand, when I tried building using `Makefile` inside `OPS/ops/c/`generated library is correctly placed inside the expected path (`$(OPS_INSTALL_PATH)/c/lib/$(OPS_COMPILER)`) mentioned in `makefiles/Makeifle.common`and `makefiles/Makefile.c_app`etc.

Why is there such a discrepancy in CMake flow?

**Comment by reguly** [comment]
The two build systems were not designed to work together, they have different ways of locating dependencies, compilers, etc.

**Comment by gihanmudalige** [comment]
Is this issue ok to be closed ?

**Comment by gihanmudalige** [comment]
@benielT I assume we can close this now ?

**Comment by benielT** [comment]
@gihanmudalige Yes.

**Comment by benielT** [comment]
@gihanmudalige Yes.
