### ISSUE TITLE
Missing pragmas for extern variables on generated OpenACC implementation 

### ISSUE THREAD

**Issue by Kamalavasan** [OP-DSL/OPS#195]
Global variables need to be copied to the device and OpenACC #pragmas are used direct compiler to allocate and update global variables on the device. Since required #pragmas are not present on generated OpenACC implementation, the compiler gives the following undefined variable error for apps/c/poisson

```
nvlink error   : Undefined reference to 'dx' in 'OpenACC/poisson_kernels_c.o'
nvlink error   : Undefined reference to 'dy' in 'OpenACC/poisson_kernels_c.o'
pgacclnk: child process exit status 2: /opt/nvidia/hpc_sdk/Linux_x86_64/23.1/compilers/bin/tools/nvdd
```

The following pragmas should be applied in the host program poisson_ops.cpp 

when declaring global variables, this will allocate memory in the device
```
double dx,dy;
#pragma acc declare copyin(dx)
#pragma acc declare copyin(dy)
```

when updating the global variable values, this will update the value in the device 
```
  dx = 0.01;
  dy = 0.01;
  #pragma acc update device(dx)
  #pragma acc update device(dy)
```

finally, global memory allocation should be indicated in the device program as well (poisson_common.h)
```
extern double dx;
extern double dy;
#pragma acc declare copyin(dx)
#pragma acc declare copyin(dy)
```

This fixes the compiler error and the test passes.

**Comment by gihanmudalige** [comment]
I have started changing the code gen to address this in https://github.com/OP-DSL/OPS/tree/fix/openacc_linking
However I think we need the new codegen capabilities to fix the host code modifications required here.

**Comment by Ashutosh-Londhe** [comment]
@gihanmudalige can we close this now.

**Comment by gihanmudalige** [comment]
Yes, given OpenACC has been discontinued we can close
