### ISSUE TITLE
TAILQ does not like realloc

### ISSUE THREAD

**Issue by reguly** [OP-DSL/OPS#68]
The realloc of OPS_block_list in ops_decl_block in ops_lib_core.c breaks the TAILQ structures inside.  Can be detected when reallocating from non-0 size to bigger, and with valgrind - modify poisson.cpp to use more than 30 blocks.

**Comment by gihanmudalige** [comment]
Currently fixing up this issue in https://github.com/OP-DSL/OPS/tree/fix/memoryissues

While the TAILQ realloc issue seems to be fixed the MPI+TIling breaks with multiple blocks. The same issue is there in the master branch when running Poisson with 4x4 grid of blocks. (pure MPI is fine)

octon {master} ~/OPS-GIT/OPS/apps/c/poisson$ export OMP_NUM_THREADS=10;$MPI_INSTALL_PATH/bin/mpirun -np 2  ./poisson_mpi_tiled OPS_TILING OPS_TILING_MAXDEPTH=10
 Tiling enabled

 Tiling enabled

 Max tiling depth across processes = 10 
Grid: 20x20 in 4x4 blocks, 10 iterations, 10 tile height
block "block 0,0" decomposed on to a processor grid of 1 x 1  
block "block 1,0" decomposed on to a processor grid of 1 x 1  
block "block 2,0" decomposed on to a processor grid of 1 x 1  
block "block 3,0" decomposed on to a processor grid of 1 x 1  
block "block 0,1" decomposed on to a processor grid of 1 x 1  
block "block 1,1" decomposed on to a processor grid of 1 x 1  
block "block 2,1" decomposed on to a processor grid of 1 x 1  
block "block 3,1" decomposed on to a processor grid of 1 x 1  
block "block 0,2" decomposed on to a processor grid of 1 x 1  
block "block 1,2" decomposed on to a processor grid of 1 x 1  
block "block 2,2" decomposed on to a processor grid of 1 x 1  
block "block 3,2" decomposed on to a processor grid of 1 x 1  
block "block 0,3" decomposed on to a processor grid of 1 x 1  
block "block 1,3" decomposed on to a processor grid of 1 x 1  
block "block 2,3" decomposed on to a processor grid of 1 x 1  
block "block 3,3" decomposed on to a processor grid of 1 x 1  
Finished block decomposition
APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
