### ISSUE TITLE
HDF5 File Write fails for mpi_tiling parallel versions

### ISSUE THREAD

**Issue by gihanmudalige** [OP-DSL/OPS#74]
It appears that writing to HDF5 files for from/after a mpi+tiling run fails. The current master branch's cloverleaf_mpi_tiling version under CLoverLeaf_3D_HDF5 demonstrates the problem. 
A fix is being looked into in the branch fix/HDF5_with_tiling

**Comment by reguly** [comment]
Just tested this, still seems to be giving issues, also with reading from HDF5 with CloverLeaf 3D HDF5. Unsure why

**Comment by gihanmudalige** [comment]
I had all its tests passed for this yesterday. Can you let me know what you ran and the order you ran then in ?

**Comment by gihanmudalige** [comment]
ok .. confirmed to have been fixed:
Author: reguly <regulyistvan@gmail.com>
Date:   Wed Jun 27 09:37:50 2018 +0100

Fixes an issue with writing HDF5 files when using tiling, and when tiling and cuda is used

Tests also passed
